# Generated by Django 6.0.6 on 2026-07-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker1', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
