# Generated by Django 6.0.6 on 2026-07-12 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker1', '0006_expenseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='group_type',
            field=models.CharField(choices=[('trip', 'Trip'), ('home', 'Home'), ('couple', 'Couple'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupexpense',
            name='split_type',
            field=models.CharField(choices=[('equally', 'Equally'), ('unequally', 'Unequally'), ('percentages', 'Percentages')], default='equally', max_length=20),
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expense_tracker1.groupexpense')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker1.groupmember')),
            ],
        ),
    ]
