# Generated by Django 6.0.6 on 2026-07-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker1', '0007_expensegroup_end_date_expensegroup_group_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='anniversary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='rent_due_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
