# Generated by Django 6.0.6 on 2026-07-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker1', '0008_expensegroup_anniversary_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/'),
        ),
    ]
