# Generated by Django 6.0.6 on 2026-08-03 10:49

import expense_tracker1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker1', '0014_expensegroup_invite_code_groupmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroup',
            name='invite_code',
            field=models.CharField(default=expense_tracker1.models.generate_invite_code, max_length=10, unique=True),
        ),
    ]
