# Generated by Django 6.0.6 on 2026-08-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker1', '0019_plaiditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_photos/'),
        ),
    ]
